### PR TITLE
Introduce Deno-based development tools for CI.

### PR DESCRIPTION
**Pull request by dajiaji**
@chris-wood I introduced a Deno-based CI framework and applied Deno fmt and lint.
Could you check and merge it?

Note that you have to remove ohttp-js/node_module directory at first and then you can run deno fmt, lint and test as follows:

```sh
deno task test
```
You can also output the npm package and run tests on the Node.js environment as follows:

```sh
deno task dnt
```

If you have any questions, feel free to ask.

### CODE REVIEW

**Comment by dajiaji** [comment]
Thanks!

As a next step, I will check to see if it works on web browsers and add it
to the CI workflow.

By the way, is the npm package name "ohttp-js" correct?
I checked the npm registry and I found that "ohttp" is not used yet. So you
can get it :-)

In my case, I had wanted to use "hpke" and "bhttp" but they were already
reserved.

Best,
Daisuke

2022年11月23日(水) 8:27 Christopher Wood ***@***.***>:

**Comment by chris-wood** [comment]
Yep, that’s a fine package name. I’ve not configured anything on npm before, but I’ll take a look at it now and try to register the name.

**Comment by dajiaji** [comment]
FYI.

As you can see in ohttp-js/deno.json, note that the latest git tag name
will be used as the npm package version.

If you want to release the npm package manually for trial, you can follow
the steps below:

```
git tag -a v0.1.0 -m "First public preview release"
deno task dnt
cd npm/
npm publish
```

Best,
Daisuke

2022年11月23日(水) 9:23 Christopher Wood ***@***.***>:

> Yep, that’s a fine package name. I’ve not configured anything on npm
> before, but I’ll take a look at it now and try to register the name.
>

**Comment by chris-wood** [comment]
Sorry for the delay in getting back to this! I tried to run `deno`, but hit the following issue:

```
✗ deno task dnt
Task dnt deno run -A dnt.ts $(git describe --tags $(git rev-list --tags --max-count=1))
[dnt] Transforming...
[dnt] Running npm install...

added 11 packages, and audited 12 packages in 883ms

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[dnt] Building project...
[dnt] Type checking...
src/node_modules/exit/test/exit_test.js:1:1 - error TS9005: Declaration emit for this file requires using private name 'setUp'. An explicit type annotation may unblock declaration emit.

1 'use strict';
  ~~~~~~~~~~~~

error: Uncaught (in promise) Error: Had 1 diagnostics.
        throw new Error(`Had ${diagnostics.length} diagnostics.`);
              ^
    at build (https://deno.land/x/dnt@0.31.0/mod.ts:315:15)
    at async file:///Users/christopherwood/dev/ohttp-js/dnt.ts:5:1
```

**Comment by dajiaji** [comment]
Now I remember.

> Note that you have to remove ohttp-js/node_module directory at first

Did you remove ohttp-js/node_modules?

**Pull request merged**
